home:
    path: /
    defaults: { _controller: Gist\Controller\EditController::createAction, _locale: en }

view:
    path: /{gist}
    defaults: { _controller: Gist\Controller\ViewController::viewAction, _locale: en }
