home:
    path: /
    defaults: {_controller: Gist\Controller\EditController::createAction, _locale: en}

view:
    path: /{gist}/{commit}
    defaults: {_controller: Gist\Controller\ViewController::viewAction, _locale: en, commit: 0}
