home:
    path: /
    defaults: {_controller: Gist\Controller\EditController::createAction, _locale: en}

clone:
    path: /clone/{gist}/{commit}
    defaults: {_controller: Gist\Controller\EditController::cloneAction, _locale: en, commit: 0}

view:
    path: /view/{gist}/{commit}
    defaults: {_controller: Gist\Controller\ViewController::viewAction, _locale: en, commit: 0}

embed:
    path: /embed/{gist}/{commit}
    defaults: {_controller: Gist\Controller\ViewController::embedAction, _locale: en, commit: 0}

embedjs:
    path: /embedjs/{gist}/{commit}
    defaults: {_controller: Gist\Controller\ViewController::embedJsAction, _locale: en, commit: 0}

raw:
    path: /raw/{gist}/{commit}
    defaults: {_controller: Gist\Controller\ViewController::rawAction, _locale: en, commit: 0}

download:
    path: /download/{gist}/{commit}
    defaults: {_controller: Gist\Controller\ViewController::downloadAction, _locale: en, commit: 0}

register:
    path: /register
    defaults: {_controller: Gist\Controller\LoginController::registerAction, _locale: en}

login:
    path: /login
    defaults: {_controller: Gist\Controller\LoginController::loginAction, _locale: en}

_login:
    path: /login
    defaults: {_controller: Gist\Controller\LoginController::loginAction, _locale: en}

login_check:
    path: /login_check

logout:
    path: /my/logout

my:
    path: /my/{page}
    defaults:
        _controller: Gist\Controller\MyController::myAction
        _locale: en
        page: 1
    requirements:
        page: \d+

revisions:
    path: /revs/{gist}
    defaults: {_controller: Gist\Controller\ViewController::revisionsAction, _locale: en}

api_list:
    path: /api/list/{apiKey}
    defaults: {_controller: Gist\Controller\ApiController::listAction, _locale: en}

api_create:
    path: /api/create/{apiKey}
    defaults: {_controller: Gist\Controller\ApiController::createAction, _locale: en}

api_update:
    path: /api/update/{gist}/{apiKey}
    defaults: {_controller: Gist\Controller\ApiController::updateAction, _locale: en}
